name: 'Trasform GitHub lab to Github skills format'
description: 'Take a config.yml, parse it into a README.md'
inputs:
  config-file:  # config.yml
    description: 'config.yml path'
    required: true
    default: 'config.yml'
  course-details-file: # course-details.md
    description: 'course-details.md path'
    required: true
    default: 'course-details.md'
  readme-file: # README.md
    description: 'README.md to generate'
    required: true
    default: 'README.md'
  inline-markdown-links:
    description: inline relative markdown files links provided in step link property.
    default: 'false'
    required: false
outputs:
  readme:
    description: 'The genereated README.md from config.yml + course-details.md'
runs:
  using: 'node16'
  main: 'dist/index.js'
