name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        config-file: 'test/config.yml'
        course-details-file: 'test/course-details.md'
        readme-file: 'test/out/readme.md'

  # ADDON Tests
  test-addons:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        config-file: 'test/config-with-files.yml'
        course-details-file: 'test/course-details.md'
        readme-file: 'test/out/readme-with-files-inline-links.md' 
        inline-markdown-links: true
    - uses: ./
      with:
        config-file: 'test/config-with-files.yml'
        course-details-file: 'test/course-details.md'
        readme-file: 'test/out/readme-with-files-no-inline-links.md' 
        inline-markdown-links: false